### ISSUE TITLE
Sharing model among worker process

### ISSUE THREAD

**Issue by mehmetilker** [eightBEC/fastapi-ml-skeleton#2]
It is a question rather than an issue.
I have gone over your code to see if there is a solution to share the model (nlp, prediction etc..) among worker processes to prevent load model for every worker and utilize async definition (which is another subject/problem) but could not see a solution.
Is there something you can advice or apply in this skeleton?

Thanks.

**Comment by eightBEC** [comment]
Hi @mehmetilker 
one approach used [in this method](https://github.com/eightBEC/fastapi-ml-skeleton/blob/f4f1e6e378093786f96d9db82ad0473645a0c7e4/fastapi_skeleton/api/routes/prediction.py#L19) is to utilize the app's state to share the model within the app. 

When talking about distributed workers, you can load the model as a singleton for each worker. For large models I can recommend to prefetch them from an object storage (e.g. S3, COS) to memory (e.g. using Redis), so that each worker can load the model initially.

Does this help?

**Comment by mehmetilker** [comment]
Hi @eightBEC 

Using App's state to load an instance for once for the whole application life time but it is meaningful if an application works on single worker.
I am starting my application with following configuration. With the current approach model state loaded to memory separately.
If we have 5 worker process it means 5*1.5GB 

```
command=/home/xproj/.env/bin/gunicorn 
    app.modelsApi.main:app 
    -w 5
    -k uvicorn.workers.UvicornWorker
    --name gunicorn_models_api
    --bind 0.0.0.0:9200
```


Your advice for the solution (loading from object store to memory) does not change the situation I think, if I understood you right.

Here is another question in SO:
https://stackoverflow.com/questions/41988915/avoiding-loading-spacy-data-in-each-subprocess-when-multiprocessing

I haven't tried but I think related :
https://docs.python.org/3/library/multiprocessing.shared_memory.html
"This module provides a class, SharedMemory, for the allocation and management of shared memory to be accessed by one or more processes on a multicore or symmetric multiprocessor (SMP) machine."

**Comment by viniciusdsmello** [comment]
Hi @mehmetilker, have you found a solution for this? I'm facing the same here.

**Comment by mehmetilker** [comment]
@viniciusdsmello  no unfortunately...

**Comment by H3zi** [comment]
You can use gunicorn [preload](https://docs.gunicorn.org/en/latest/settings.html#preload-app) option to download your models only once, the workers fork will happen after the preload.
See this [SO answer](https://stackoverflow.com/questions/42439553/how-to-share-in-memory-resources-between-flask-methods-when-deploying-with-gunic/42440784#42440784) for more info.
(Haven't tested it with FastAPI)

**Comment by codespearhead** [comment]
@mehmetilker Did the above solution work? If so, can you close this issue?

**Comment by mehmetilker** [comment]
No. Also not working on the project for a long time. Since I assume few years passed there should be a better way to solve the problem.
